#!/usr/bin/env python3
"""vault_index: keep an auto-generated index block in an index.md at every folder level of a vault.

Usage: vault_index.py [--vault PATH] [--dry] [--follow-symlink NAME ...]
  --vault PATH            vault root (or env WAY_VAULT)
  --dry                   print what would change, write nothing
  --follow-symlink NAME   follow this symlinked folder (repeatable; default: none, symlinks are only listed)

Stdlib only, idempotent, writes only between the auto-index markers. Subfolders that are git repos
are listed as "repo, not indexed" and never entered. A pre-existing index.md is backed up once to
index.md.bak before its first rewrite.
"""
import argparse
import datetime
import os
import re
import shutil
import sys

SKIP_DIRS = {".obsidian", ".git", "node_modules", "graphify-out", ".trash"}
BIG = 300
START, END = "<!-- auto-index:start -->", "<!-- auto-index:end -->"


def is_md(name):
    return name.endswith(".md") and name != "index.md" and not name.startswith(".")


def title(path):
    try:
        with open(path, encoding="utf-8", errors="replace") as f:
            lines = f.read(4096).splitlines()
    except OSError:
        return ""
    i = 0
    if lines and lines[0].strip() == "---":
        for j in range(1, len(lines)):
            if lines[j].strip() == "---":
                i = j + 1
                break
    first = ""
    for ln in lines[i:]:
        ln = ln.strip()
        if not ln:
            continue
        m = re.match(r"#{1,6}\s+(.*)", ln)
        if m:
            return m.group(1).strip()[:80]
        if not first:
            first = ln
    return first[:80]


def month(path, name):
    m = re.match(r"(\d{4})-(\d{2})-\d{2}", name)
    if m:
        return f"{m.group(1)}-{m.group(2)}"
    return datetime.datetime.fromtimestamp(os.path.getmtime(path)).strftime("%Y-%m")


class Node:
    def __init__(self, path):
        self.path, self.notes, self.subs, self.links, self.repos, self.total = path, [], [], [], [], 0


def scan(path, seen, follow):
    real = os.path.realpath(path)
    if real in seen:
        return None
    seen = seen | {real}
    n = Node(path)
    try:
        entries = sorted(os.scandir(path), key=lambda e: e.name)
    except OSError:
        return None
    for e in entries:
        if e.name.startswith(".") or e.name in SKIP_DIRS:
            continue
        if e.is_symlink():
            if e.is_dir():
                if e.name in follow:
                    c = scan(e.path, seen, follow)
                    if c:
                        n.subs.append((e.name, c))
                else:
                    n.links.append(e.name)
            continue
        if e.is_dir():
            if os.path.exists(os.path.join(e.path, ".git")):  # git repo = code, never write inside
                n.repos.append(e.name)
                continue
            c = scan(e.path, seen, follow)
            if c:
                n.subs.append((e.name, c))
        elif e.is_file() and is_md(e.name):
            n.notes.append(e.name)
    n.total = len(n.notes) + sum(c.total for _, c in n.subs)
    return n


def block(n):
    out = [START, "_Auto-generated by the vault-index skill: do not edit between the markers._", ""]
    for name, c in n.subs:
        if c.total:
            out.append(f"- Folder [[{name}/index|{name}/]]: {c.total} notes")
    for name in n.links:
        out.append(f"- Folder {name}/ (symlink, not indexed)")
    for name in n.repos:
        out.append(f"- Folder {name}/ (repo, not indexed)")
    if len(n.notes) > BIG:
        by = {}
        for f in n.notes:
            k = month(os.path.join(n.path, f), f)
            by[k] = by.get(k, 0) + 1
        for k in sorted(by):
            out.append(f"- {k}: {by[k]} notes")
    else:
        for f in n.notes:
            t = title(os.path.join(n.path, f))
            out.append(f"- [[{f[:-3]}]]" + (f": {t}" if t else ""))
    out.append(END)
    return "\n".join(out)


def apply(n, root, dry, stats):
    for _, c in n.subs:
        apply(c, root, dry, stats)
    if n.total == 0:
        return
    ip = os.path.join(n.path, "index.md")
    b = block(n)
    if os.path.exists(ip):
        with open(ip, encoding="utf-8") as f:
            old = f.read()
        if START in old and END in old:
            new = re.sub(re.escape(START) + r".*?" + re.escape(END), lambda m: b, old, count=1, flags=re.S)
        else:
            new = old.rstrip("\n") + "\n\n" + b + "\n"
    else:
        old = None
        new = f"# {os.path.basename(n.path) or 'Vault'}\n\n" + b + "\n"
    if new == old:
        return
    stats["changes"] += 1
    print(("WOULD " if dry else "") + ("CREATE " if old is None else "UPDATE ") + os.path.relpath(ip, root))
    if dry:
        return
    if old is not None and not os.path.exists(ip + ".bak"):
        shutil.copy2(ip, ip + ".bak")
    with open(ip, "w", encoding="utf-8") as f:
        f.write(new)
    stats["written"] += 1


def main():
    ap = argparse.ArgumentParser(description="Maintain auto-index blocks in index.md files of a vault.")
    ap.add_argument("--vault", default=os.environ.get("WAY_VAULT"))
    ap.add_argument("--dry", action="store_true")
    ap.add_argument("--follow-symlink", action="append", default=[], metavar="NAME")
    a = ap.parse_args()
    if not a.vault:
        ap.error("vault path required: pass --vault PATH or set WAY_VAULT")
    root = os.path.abspath(os.path.expanduser(a.vault))
    if not os.path.isdir(root):
        ap.error(f"not a directory: {root}")
    tree = scan(root, frozenset(), set(a.follow_symlink))
    stats = {"changes": 0, "written": 0}
    apply(tree, root, a.dry, stats)
    print(f"vault_index: {'DRY ' if a.dry else ''}changes={stats['changes']} written={stats['written']} notes_total={tree.total}")


if __name__ == "__main__":
    main()
