#!/usr/bin/env bash
# way-stack SessionEnd hook — writes session log to vault + entry in log.md
# Path placeholder __VAULT_PATH__ replaced by /stack-bootstrap at install time.

set -eu

VAULT="__VAULT_PATH__"
[ -d "$VAULT" ] || exit 0

TS=$(date +%Y-%m-%d-%H%M)
PROJ=$(basename "$PWD")
LOG_DIR="$VAULT/04_SESSIONS"
mkdir -p "$LOG_DIR"
LOGFILE="$LOG_DIR/$TS-$PROJ.md"

{
  echo "---"
  echo "type: session"
  echo "date: $(date +%Y-%m-%d)"
  echo "project: $PROJ"
  echo "cwd: $PWD"
  echo "---"
  echo ""
  echo "# Session — $PROJ ($TS)"
  echo ""
  echo "Working directory: \`$PWD\`"
  echo ""
  echo "_Auto-generated by way-stack SessionEnd hook. Add notes below._"
} > "$LOGFILE"

{
  echo ""
  echo "## [$(date +%Y-%m-%d)] session | $PROJ"
  echo "[[04_SESSIONS/$TS-$PROJ]]"
} >> "$VAULT/log.md"

exit 0
