#!/usr/bin/env python3
"""Append '## API MAP' to every project CLAUDE.md under a root. Sonnet headless, evidence = grep hits only.
Usage: api_map.py <root> [max_runs]
Hard stops: MAX runs, 5 consecutive failures, 180s per run. Append-only, never rewrites existing text,
skips files that already have the section (safe to re-run). Regex evidence only, no AST: fix tables by hand."""
import subprocess, sys, re, os, time, json
if len(sys.argv)<2: sys.exit(__doc__)
VAULT=os.path.abspath(os.path.expanduser(sys.argv[1])); STATE=os.path.expanduser('~/.claude/token-budget'); os.makedirs(STATE,exist_ok=True)
LOG=os.path.join(STATE,'api_map.log'); NOMCP=os.path.join(STATE,'nomcp.json')
if not os.path.exists(NOMCP): open(NOMCP,'w').write('{"mcpServers": {}}')
MAX=int(sys.argv[2]) if len(sys.argv)>2 else 70
MODEL=os.environ.get('API_MAP_MODEL','sonnet')
SKIP=('_archive','node_modules','.git')
PAT=r'requests\.|httpx|aiohttp|fetch\(|axios|graphql|api\.|_TOKEN|_KEY|_SECRET|Client\(|class \w*(Client|API|Api)\b|def (get|post|call|fetch|query)_'
def log(m): open(LOG,'a').write(time.strftime('%H:%M:%S ')+m+'\n'); print(m, flush=True)
def evidence(d):
    r=subprocess.run(['grep','-rInE','--include=*.py','--include=*.js','--include=*.ts','--include=*.sh','--include=*.mjs',
        '--exclude-dir=node_modules','--exclude-dir=.git','--exclude-dir=venv','--exclude-dir=.venv','--exclude-dir=__pycache__','-m','3',PAT,d],capture_output=True,text=True)
    lines=[l[len(d)+1:][:200] for l in r.stdout.splitlines()]
    files=subprocess.run(['find',d,'-maxdepth','2','-type','f','(','-name','*.py','-o','-name','*.js','-o','-name','*.ts','-o','-name','*.sh',')','-not','-path','*/node_modules/*','-not','-path','*/.git/*'],capture_output=True,text=True).stdout.splitlines()
    return lines[:120], [f[len(d)+1:] for f in files][:80]
def run(d):
    hits,files=evidence(d)
    if len(hits)<2: return 'no-evidence'
    prompt=f"""Project dir: {d}
Files (max 80):
{chr(10).join(files)}
Grep hits for API clients (file:line:code):
{chr(10).join(hits)}

Task: write ONLY a markdown table (no prose, no code fence) with header exactly:
| API | File | Entry point | Auth | Notes |
One row per external/internal API client actually visible in the evidence (third-party SaaS APIs, internal http servers, CLI wrappers...). Entry point = function/class name from the evidence. Auth = env var / keychain name seen, else "?". Max 12 rows. NEVER invent: if not in evidence, leave it out. If nothing real, output exactly: NONE"""
    try:
        r=subprocess.run(['claude','-p','--model',MODEL,'--output-format','text','--max-turns','1','--no-session-persistence',
            '--strict-mcp-config','--mcp-config',NOMCP,'--setting-sources','',prompt],
            capture_output=True,text=True,timeout=180,cwd=d)
    except subprocess.TimeoutExpired: return 'timeout'
    out=r.stdout.strip()
    if out=='NONE': return 'none'
    rows=[l for l in out.splitlines() if l.startswith('|')]
    if len(rows)<3 or 'Entry point' not in rows[0]: return 'bad-output: '+out[:80].replace('\n',' ')
    with open(os.path.join(d,'CLAUDE.md'),'a') as f:
        f.write('\n\n## API MAP\n<!-- generated by way-stack api_map.py (cheap model, grep evidence only). Fix by hand. Source of truth for models: if it is missing here, grep BEFORE saying it does not exist. -->\n'+'\n'.join(rows)+'\n')
    return f'ok {len(rows)-2} rows'
dirs=sorted(os.path.dirname(l) for l in subprocess.run(['find',VAULT,'-maxdepth','3','-name','CLAUDE.md'],capture_output=True,text=True).stdout.splitlines() if not any(s in l for s in SKIP))
done=fails=0
for d in dirs:
    if done>=MAX: log('STOP max'); break
    if '## API MAP' in open(os.path.join(d,'CLAUDE.md'),errors='ignore').read(): continue
    res=run(d); done+=1; log(f'{d[len(VAULT)+1:]}: {res}')
    fails = fails+1 if res.startswith(('bad','timeout')) else 0
    if fails>=5: log('STOP 5 fail'); break
log(f'DONE {done} projects')
